---
- name: Generic new poll for new records in ServiceNow
  hosts: all
  sources: 
    - name: Watch for any updated table
      servicenow.itsm.records:
        table: sc_request
        interval: 5
  rules:

    - name: New record created and debug
      condition: true 
      action: 
        run_job_template:
          name: "Cloud | AWS | Create VM"
          organization: "Ansible Product Demos (APD)"
          job_args:
            extra_vars:
              create_vm_aws_region: "{{ event.payload.aws_region }}"
              create_vm_vm_name: "{{ event.payload.vm_name }}"
              create_vm_vm_owner: "{{ event.payload.vm_owner }}"
              create_vm_vm_deployment: "{{ event.payload.vm_deployment }}"
              create_vm_vm_environment: "{{ event.payload.vm_environment }}"
        debug:
